{% set name = "pyStreamer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d8da0914612da9a2ec76703fb61fb181a062b3e94999ccaff179a274b2b0b61

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - streamer

about:
  home: https://github.com/Arnoldosmium/pystreamer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lazy evaluating, memory efficient, chain-able generator for python; inspired by the syntactical sugar of Java stream
  dev_url: https://github.com/Arnoldosmium/pystreamer

extra:
  recipe-maintainers:
    - Arnoldosmium
