{% set name = "pyStreamer" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c02ce1d1f7070142fcd4c4c42b894c4a825346b3810bb32fc2f9d5c782a4ead

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - streamer

about:
  home: https://github.com/Arnoldosmium/pystreamer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lazy evaluating, memory efficient, chain-able generator for python; inspired by the syntactical sugar of Java stream
  dev_url: https://github.com/Arnoldosmium/pystreamer

extra:
  recipe-maintainers:
    - Arnoldosmium
