travis:
  secure:
    BINSTAR_TOKEN: ukTPZNbsWeby99C6X07BpNRVaOToPIrBijVbtk2nLAS98E8icRMAUzM03qt9a8fkmQv7+uuyTBTvqBlROGUFqM3IzAg8J/cRBjedkk5GiX4Z5pBcCE5S+z8a1YZGanBAzNcOzSYxk19WUrmB6Ev5I0GHrsvMpUHCAGSEKRNPU4P/bMP+JI83YMwgstO458uwPkY/7dRJ6tRZFnmL/HfJozsR6iczphz2+4+MTov4reHtnUuyBb6ysN9JjkIOPWpe8hZOgdAEQZBEzBqb/sbByX7rnVPWXGyqfB0xSPRmXS/oJTLIY+ToEMqrcNWEF4uSqi2/UeRVJ6ZaEejfhpyJtkthRMI+3y4U1AaNR99GGVDIf3+wkeg10M84rot9CBx21Eh2Kad5P9y+iBcAVq88EGGu/CkCIKByCwqESPdsvHmKAj1OEEVIriJgHUqCxMoOnUFEjFpiwIchwoGRv5p3m134pkMDhuRLG4ELIPoXRyJHMGUUjrnwJj1PR7OrlQuigTA5j4iWCeuylXZ8gO6Hj57ryRoiOC+sKpdv/a4glGnNY4QNvA3envqVyBE+aE1XN2hz/dGjzPW02KOCgcxAo8XCKEmOio2UUiPvPFXkqBYBEQ4ytx5cXIZqTg1LBvLhwwvT0na1hwkVZb49AMViKQWTURV7iINRWASMqTf/MT8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
